# Generated by Django 4.0.4 on 2022-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='contorno',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='patologia',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='talla',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(default='No informado', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='email',
            field=models.EmailField(default='No informado', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(default='No informado', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
